# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_in_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_time', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Group_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(max_length=220)),
                ('name_surname', models.CharField(max_length=220)),
                ('Age', models.IntegerField()),
                ('Parent_name', models.CharField(max_length=220)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Group_type')),
            ],
        ),
        migrations.AddField(
            model_name='group_in_time',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Group_type'),
        ),
    ]
