# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171106_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_in_time',
            name='Group',
        ),
        migrations.AddField(
            model_name='group_type',
            name='group_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group_in_time',
        ),
    ]
