# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_group_type_group_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_in_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_time', models.CharField(max_length=220)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Group_type')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Group_in_time'),
        ),
    ]
