# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20171112_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name_surname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='person',
            name='child_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
