# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_group_in_time_exactly_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_in_time',
            name='Group_time',
        ),
    ]
