# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-19 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20171119_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Count_of_payment_in_trimester',
        ),
    ]
