# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_delete_count_of_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tan_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
