# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_cashvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='Pay_in_this_tri',
        ),
        migrations.AddField(
            model_name='person',
            name='Pay_in_this_tri_1',
            field=models.SmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Pay_in_this_tri_2',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='Pay_in_this_tri_3',
            field=models.SmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
