# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_auto_20171121_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvalue',
            name='vat_value',
            field=models.DecimalField(decimal_places=2, default=0.29, max_digits=6),
            preserve_default=False,
        ),
    ]
