# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_auto_20171123_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvalue',
            name='Count_of_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashvalue',
            name='Pay_value',
            field=models.DecimalField(decimal_places=2, default=29, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cashvalue',
            name='tan_value',
            field=models.DecimalField(decimal_places=2, default=0.14, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cashvalue',
            name='vat_value',
            field=models.DecimalField(decimal_places=2, default=0.29, max_digits=6),
        ),
    ]
