# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_auto_20171123_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_in_time',
            name='Time_minutes',
            field=models.ImageField(default=14, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group_in_time',
            name='Time_hour',
            field=models.IntegerField(),
        ),
    ]
